config/routes.rb
Rails.application.routes.draw do
  # 顧客用
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   namespace :admin do
    root to: "homes#top"
    get "about", to: "homes#about"
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders
    resources :order_details
   end

   scope module: :public do
    root to: "homes#top"
    get "about", to: "homes#about"
    resources :items, only: [:index, :show]
    resources :customers, only: [:edit,:update,:show] do
      collection do
        # 退会確認画面
        get  '/customers/check' => 'customers#check'
        # 論理削除用のルーティング
        patch  '/customers/withdraw' => 'customers#withdraw'
      end
    end
    resources :cart_items,only: [:index,:update,:create,:destroy] do
      collection do
        delete '/all_destroy' => 'cart_items#all_destroy'
      end
    end
    resources :orders, only: [:new, :create, :index, :show]do
      collection do
        post "confirm"
        get "complete"
      end
    end
    resources :addresses
    end
   end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postcode + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :quantity, presence: true

  def subtotal
    item.add_tax_price*quantity
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  # 会員フルネーム(しばじゅん）
  def full_name
    self.last_name + self.first_name
  end
  def kana_full_name
    self.kana_last_name + self.kana_first_name
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end




end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

has_many :order_details, dependent: :destroy
has_many :cart_items, dependent: :destroy
belongs_to :genre
has_one_attached :image
validates :image, presence: true
validates :name, presence: true
validates :description, presence: true
validates :price, presence: true

def add_tax_price
  (self.price * 1.10).round
end

def self.looks(word)
  Item.where("name LIKE?","%#{word}%")
end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
	enum status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def subtotal
    item.add_tax_price*quantity
  end

  def self.ordertotal
    sum(:quantity)
  end

  enum making_status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  
  private

   def customer_params
     params.require(:customer).permit(:first_name,:last_name,:kana_first_name,:kana_last_name,:postcode,:address,:phone_number,:email,:is_deleted)
   end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController


  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
		if @genre.save
		   @genres = Genre.all
		   render :index
		else
		  @genres = Genre.all
		   redirect_back(fallback_location: root_path)
		end

  end

  def edit
    @genre = Genre.find(params[:id])

  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      redirect_back(fallback_location: root_path)
    end
  end


 private
  def genre_params
	  params.require(:genre).permit(:name)
	end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @orders = @customer.orders.page(params[:page]).per(10)
    else
      @orders = Order.page(params[:page]).per(10)
    end
  end

  private
  def order_params
    params.require(:order).permit(:postcode, :address, :name, :payment_method,)
  end

  def address_params
    params.require(:order).permit(:postcode, :address, :name)
  end



end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def index
    if params[:word]
      @items = Item.looks(params[:word]).page(params[:page])
    else
      @items = Item.all.page(params[:page])
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
      @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
      @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :description, :genre_id, :price, :is_sold_out)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController


  def show
  @order = Order.find(params[:id])
  @order_details = @order.order_details
  @total = @order_details.inject(0) { |sum, item| sum + item.subtotal }
  end

  def update
  @order = Order.find(params[:id])
  if @order.update(order_params)
     @order.order_details.update_all(making_status: 1) if @order.status == "入金確認"
  end
  redirect_to admin_order_path
  end


private
  def order_params
  params.require(:order).permit(:status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #ここの記述は、public/registrationコントローラーに記載した（しばじゅん）
  #before_action :configure_permitted_parameters, if: :devise_controller?
  #protected
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
    <div class="row">
       <div class="col-10 mx-auto">
         <h3 class="my-5 text-center"><%= @customer.full_name %>さんの会員情報編集</h3>
         <%= form_with model: @customer, url: admin_customer_path, local:true do |f| %>
        <div class="field-row">
          <%= f.label :"会員ID", class:"col-4" %>
          <%= f.label :"#{@customer.id}" %>
        </div>
        <div class="field-row">
          <%= f.label :"氏名", class:"col-4" %>
          <%= f.text_field :last_name, class:"col-3" %>
          <%= f.text_field :first_name, class:"col-3" %>
        </div>
        <div class="field-row">
          <%= f.label :"フリガナ", class:"col-4" %>
          <%= f.text_field :kana_last_name, class:"col-3" %>
          <%= f.text_field :kana_first_name, class:"col-3" %>
        </div>
        <div class="field-row">
          <%= f.label :"郵便番号", class:"col-4" %>
          <%= f.text_field :postcode, class:"col-3" %>
        </div>
        <div class="field-row">
          <%= f.label :"住所", class:"col-4" %>
          <%= f.text_field :address, class:"col-7" %>
        </div>
        <div class="field-row">
          <%= f.label :"電話番号", class:"col-4" %>
          <%= f.text_field :phone_number, class:"col-3" %>
        </div>
        <div class="field-row">
          <%= f.label :"メールアドレス", class:"col-4" %>
          <%= f.text_field :email, class:"col-3" %>
        </div>
        <div class="form-group">
          <%= f.label :"会員ステータス", class:"col-4" %>
          <%= f.radio_button :is_deleted, false %>
          <%= f.label :is_deleted, "有効" %>
          <%= f.radio_button :is_deleted, true %>
          <%= f.label :is_deleted, "退会" %>
        </div>
        <div class="form-group col-11 d-flex justify-content-around">
          <%= f.submit '変更を保存', class: "btn btn-success" %>
        </div>
      <% end %>
       </div>
    </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h3 class="text-center mt-5", style="margin:auto; width:200px;">会員一覧</h3>
    <div class="col-10 mx-auto">
      <table class="table mt-5">
      <thead  class="table-secondary">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
             <td class="info col-xs-1">
                <%= customer.id %>
             </td>
             <td class="text-left">
                <%= link_to customer.full_name, admin_customer_path(customer) %>
             </td>
             <td class="text-left">
                <%= customer.email %>
             </td>
             <td class="col-xs-2">
                <% if customer.is_deleted == true%>
                  <p class="text-danger">退会済</p>
                <% else %>
                  <p class="text-success">有効</p>
                <% end %>
             </td>
         </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
  <div class="d-flex justify-content-center"><%= paginate @customers, theme: 'twitter-bootstrap-4' %></div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 mx-auto">
      <h3 class="my-5 text-center"><%= @customer.full_name %>さんの会員詳細</h3>
      <table class="table">
        <tr>
          <th class="text-left">会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th class="text-left">氏名</th>
          <td><%= @customer.full_name %></td>
        </tr>
        <tr>
          <th class="text-left">フリガナ</th>
          <td><%= @customer.kana_full_name %></td>
        </tr>
        <tr>
          <th class="text-left">郵便番号</th>
          <td><%= @customer.postcode %></td>
        </tr>
        <tr>
          <th class="text-left">住所</th>
          <td><%= @customer.address %></td>
        </tr>
          <th class="text-left">電話番号</th>
          <td><%= @customer.phone_number %></td>
        </tr>
        </tr>
          <th class="text-left">メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
          <th class="text-left">会員ステータス</th>
          <% if @customer.is_deleted == true %>
            <td class="text-danger">退会済み</td>
          <% else %>
            <td class="text-success">有効</td>
          <% end %>
        </tr>
        <tr>
          <th></th>
          <td class="d-flex">
            <p><%= link_to "編集する",edit_admin_customer_path, class:"btn btn-success" %></p>
            <p class="offset-3"><%= link_to "注文履歴一覧を見る", admin_root_path(customer_id: @customer.id), class:"btn btn-primary" %></p>
            <!--オーダー機能が実装されたら、admin_orders_pathでちゃんと飛ぶか確認。（しばじゅん）-->
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>