config/routes.rb
Rails.application.routes.draw do
  # 顧客用
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   namespace :admin do
    root to: "homes#top"
    get "about", to: "homes#about"
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders
    resources :order_details
   end

   scope module: :public do
    root to: "homes#top"
    get "about", to: "homes#about"
    resources :items, only: [:index, :show]
    resources :customers, only: [:edit,:update,:show] do
      collection do
        # 退会確認画面
        get  '/customers/check' => 'customers#check'
        # 論理削除用のルーティング
        patch  '/customers/withdraw' => 'customers#withdraw'
      end
    end
    resources :cart_items,only: [:index,:update,:create,:destroy] do
      collection do
        delete '/all_destroy' => 'cart_items#all_destroy'
      end
    end
    resources :orders, only: [:new, :create, :index, :show]do
      collection do
        post "confirm"
        get "complete"
      end
    end
    resources :addresses
    end
   end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postcode + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :quantity, presence: true

  def subtotal
    item.add_tax_price*quantity
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  # 会員フルネーム(しばじゅん）
  def full_name
    self.last_name + self.first_name
  end
  def kana_full_name
    self.kana_last_name + self.kana_first_name
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end




end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

has_many :order_details, dependent: :destroy
has_many :cart_items, dependent: :destroy
belongs_to :genre
has_one_attached :image
validates :image, presence: true
validates :name, presence: true
validates :description, presence: true
validates :price, presence: true

def add_tax_price
  (self.price * 1.10).round
end

def self.looks(word)
  Item.where("name LIKE?","%#{word}%")
end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
	enum status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def subtotal
    item.add_tax_price*quantity
  end

  def self.ordertotal
    sum(:quantity)
  end

  enum making_status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController


  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
		if @genre.save
		   @genres = Genre.all
		   render :index
		else
		  @genres = Genre.all
		   redirect_back(fallback_location: root_path)
		end

  end

  def edit
    @genre = Genre.find(params[:id])

  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      redirect_back(fallback_location: root_path)
    end
  end


 private
  def genre_params
	  params.require(:genre).permit(:name)
	end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @orders = @customer.orders.page(params[:page]).per(10)
    else
      @orders = Order.page(params[:page]).per(10)
    end
  end

  private
  def order_params
    params.require(:order).permit(:postcode, :address, :name, :payment_method,)
  end

  def address_params
    params.require(:order).permit(:postcode, :address, :name)
  end



end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def index
    if params[:word]
      @items = Item.looks(params[:word]).page(params[:page])
    else
      @items = Item.all.page(params[:page])
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
      @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
      @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :description, :genre_id, :price, :is_sold_out)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController


  def show
  @order = Order.find(params[:id])
  @order_details = @order.order_details
  @total = @order_details.inject(0) { |sum, item| sum + item.subtotal }
  end

  def update
  @order = Order.find(params[:id])
  if @order.update(order_params)
     @order.order_details.update_all(making_status: 1) if @order.status == "入金確認"
  end
  redirect_to admin_order_path
  end


private
  def order_params
  params.require(:order).permit(:status)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected
  def after_sign_in_for_path(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #ここの記述は、public/registrationコントローラーに記載した（しばじゅん）
  #before_action :configure_permitted_parameters, if: :devise_controller?
  #protected
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
   <div class="row">
    <div class="col-10 mx-auto">
        <h3 class="ml-5 my-5">ジャンル編集</h3>
        <div class="form-group">
            <%= form_with model: @genre,url: admin_genre_path do |f| %>
              <%= f.label "ジャンル名" %>
              <%= f.text_field :name,id:"inputname" %>
            <%=f.submit "変更を保存", class:"btn btn-success my-3 mr-3" %>
            </div>
            <% end %>
        </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 mx-auto">
      <h3 class="my-5 ml-5">ジャンル一覧・追加</h3>
      <%= form_with model: @genre,url: admin_genres_path do |f| %>
        <%= f.label :name, "ジャンル名" %>
        <%= f.text_field :name %>
        <%= f.submit "新規登録", class:"btn btn-success" %>
      <% end %>
      <table class='table mt-5 w-50'>
        <thead style="background-color:#d3d3d3;">
          <tr>
            <th>ジャンル</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @genres.each do |genre| %>
        <tbody>
          <th><%= genre.name %></th>
          <th><%= link_to "編集する", edit_admin_genre_path(genre), class:"btn btn-success py-0" %></th>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mx-auto">
      <h3 class="text-center mb-4 mt-5", style="margin:auto; width:230px;">商品編集</h3>
      <%= form_with model: @item, url: admin_item_path do |f| %>
        <div class="form-group">
          <%= f.label :商品画像, style: "margin-right:60px;" %>
          <%= f.file_field :image, accept: "image/*" %>
        </div>
        <div class="form-group">
          <%= f.label :商品名, style: "margin-right:75px;" %>
          <%= f.text_field :name, placeholder: "商品名" %>
        </div>
        <div class="form-group">
          <%= f.label :商品説明, style: "margin-right:60px;", class: 'align-top' %>
          <%= f.text_area :description, placeholder: "ここに説明文を記述します", size: "30x5" %>
        </div>
        <div class="form-group">
          <%= f.label :ジャンル, style: "margin-right:60px;" %>
          <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), include_blank: "選択してください" %>
        </div>
        <div class="form-group">
          <%= f.label :税抜価格, style: "margin-right:60px;" %>
          <%= f.number_field :price, placeholder: "1000" %>円
        </div>
        <div class="form-group d-flex">
          <%= f.label :販売ステータス %>
        <div class="ml-3">
          <%= f.radio_button :is_sold_out, "false" %>
          <%= f.label :is_sold_out_false, "販売中" %>
        </div>
        <div class="ml-3">
          <%= f.radio_button :is_sold_out, "true" %>
          <%= f.label :is_sold_out_true, "販売停止中" %>
        </div>
        </div>
        <div class="form-group">
          <%= f.submit "変更を保存", class: "btn btn-success rounded text-white" , style: "margin-left:200px;" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 mx-auto">
      <h3 class="text-center mt-5", style="margin:auto; width:200px;">商品一覧</h3>
      <%= link_to new_admin_item_path, class: "d-flex justify-content-end text-decoration-none mb-2" do %>
      <i class="fas fa-plus-circle fa-2x"></i>
      <% end %>
      <table class="table mx-auto">
        <thead class="table-secondary">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to item.name, admin_item_path(item) %></td>
              <td><%= item.price.to_s(:delimited, delimiter: ',') %></td>
              <td><%= item.genre.name %></td>
              <% if item.is_sold_out %>
                <td class="text-danger">販売停止中</td>
              <% else %>
                <td class="text-success">販売中</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center"><%= paginate @items, theme: 'twitter-bootstrap-4' %></div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-6 mx-auto">
      <h3 class="mb-4 mt-5", style="margin:auto; width:200px;">商品新規登録</h3>
      <%= form_with model: @item, url: admin_items_path do |f| %>
        <div class="form-group">
          <%= f.label :商品画像, style: "margin-right:60px;" %>
          <%= f.file_field :image, accept: "image/*" %>
        </div>
        <div class="form-group">
          <%= f.label :商品名, style: "margin-right:75px;" %>
          <%= f.text_field :name, placeholder: "商品名" %>
        </div>
        <div class="form-group">
          <%= f.label :商品説明, style: "margin-right:60px;", class: 'align-top' %>
          <%= f.text_area :description, placeholder: "ここに説明文を記述します", size: "30x5" %>
        </div>
        <div class="form-group">
          <%= f.label :ジャンル, style: "margin-right:60px;" %>
          <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), include_blank: "選択してください" %>
        </div>
        <div class="form-group">
          <%= f.label :税抜価格, style: "margin-right:60px;" %>
          <%= f.number_field :price, placeholder: "1000" %>円
        </div>
        <div class="form-group d-flex">
          <%= f.label :販売ステータス %>
        <div class="ml-3">
          <%= f.radio_button :is_sold_out, false %>
          <%= f.label :is_sold_out_false, "販売中" %>
        </div>
        <div class="ml-3">
          <%= f.radio_button :is_sold_out, true %>
          <%= f.label :is_sold_out_true, "販売停止中" %>
        </div>
        </div>
        <div class="form-group">
          <%= f.submit "新規登録", class: "btn btn-success rounded text-white" , style: "margin-left:200px;" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row"><h3 class="text-center mt-5", style="margin:auto; width:200px;">商品詳細</h3></div>
  <div class="row">
    <div class="col-4 ml-5 mt-5">
      <%= image_tag @item.image, size: "300x200"%>
    </div>
    <div class="col-7 mt-5">
      <table class="table table-borderless">
        <tr>
          <th>商品名</th>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @item.description %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th>税込価格(税抜価格)</th>
          <td><%= @item.add_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <% if @item.is_sold_out %>
            <td class="text-danger">販売停止中</td>
          <% else %>
            <td class="text-success">販売中</td>
          <% end %>
        </tr>
      </table>
      <%= link_to "編集する", edit_admin_item_path, class: "btn btn-success rounded text-white" %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class='col-10 mx-auto'>
      <h3 class="text-center my-5 ml-auto">注文履歴詳細</h3>
    <div class='row'>
      <div class="col-12 mb-5">
        <table class='table-borderless w-50'>
        <tr><th>購入者</th>
        <td>
          <%= link_to admin_customer_path(@order.customer) do%>
          <%= @order.customer.full_name %>
          <% end %>
        </td>
        </tr>
        <tr><th>注文日</th><td><%= @order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td></tr>
        <tr><th>配送先</th>
          <td>
            〒<%= @order.postcode %> <%= @order.address %>
            </td>
            <tr>
              <th></th>
              <td><%= @order.name %></td>
            </tr>
          </tr>
        <tr><th>支払方法</th><td><%= @order.payment_method_i18n %></td></tr>
        <tr><th>注文ステータス</th>
          <td><%= form_with model: @order, url: admin_order_path do |f| %>
                <%= f.select :status, Order.statuses.keys,class:"status"%>
                <%= f.submit '更新', class:"btn btn-sm btn-success" %>
                <% end %>
          </td>
        </tr>
      </table>
      </div>

    </div>
    <div class="row">
      <div class="col-9">
        <table class='table'>
        <thead style="background-color:#d3d3d3;">

          <tr>
            <th>商品名</th>
            <th>価格（税込み）</th>
            <th>注文個数</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>

        <% @order_details.each do |order_detail| %>

        <tbody>
            <th><%= order_detail.item.name %></th>
            <th><%= order_detail.item.add_tax_price.to_s(:delimited) %></th>
            <th><%= order_detail.quantity %></th>
            <th><%= order_detail.subtotal.to_s(:delimited, delimiter: ',') %></th>
            <th>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail) do |f|%>
                <%= f.select :making_status, OrderDetail.making_statuses.keys, class:"making_status"%>
                <%= f.submit "更新", class:"btn btn-success"%>
              <% end %>
            </th>
        </tbody>
          <% end %>
      </table>
      </div>
      <div class="col-3">
         <table class='table table-borderless '>
        <tr><th>商品合計</th><td><%= @total.to_s(:delimited, delimiter: ',') %></td></tr>
        <tr><th>送料</th><td><%= @order.postage %></td></tr>
        <tr><th>請求金額合計</th><td><%= @order.billing_amount.to_s(:delimited, delimiter: ',') %></td></tr>
      </table>
      </div>
    </div>

    </div>
  </div>
</div>