config/routes.rb
Rails.application.routes.draw do
  # 顧客用
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   namespace :admin do
    root to: "homes#top"
    get "about", to: "homes#about"
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders
    resources :order_details
   end

   scope module: :public do
    root to: "homes#top"
    get "about", to: "homes#about"
    resources :items, only: [:index, :show]
    resources :customers, only: [:edit,:update,:show] do
      collection do
        # 退会確認画面
        get  '/customers/check' => 'customers#check'
        # 論理削除用のルーティング
        patch  '/customers/withdraw' => 'customers#withdraw'
      end
    end
    resources :cart_items,only: [:index,:update,:create,:destroy] do
      collection do
        delete '/all_destroy' => 'cart_items#all_destroy'
      end
    end
    resources :orders, only: [:new, :create, :index, :show]do
      collection do
        post "confirm"
        get "complete"
      end
    end
    resources :addresses
    end
   end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postcode + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :quantity, presence: true

  def subtotal
    item.add_tax_price*quantity
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  # 会員フルネーム(しばじゅん）
  def full_name
    self.last_name + self.first_name
  end
  def kana_full_name
    self.kana_last_name + self.kana_first_name
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end




end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

has_many :order_details, dependent: :destroy
has_many :cart_items, dependent: :destroy
belongs_to :genre
has_one_attached :image
validates :image, presence: true
validates :name, presence: true
validates :description, presence: true
validates :price, presence: true

def add_tax_price
  (self.price * 1.10).round
end

def self.looks(word)
  Item.where("name LIKE?","%#{word}%")
end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
	enum status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def subtotal
    item.add_tax_price*quantity
  end

  def self.ordertotal
    sum(:quantity)
  end

  enum making_status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController


  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
		if @genre.save
		   @genres = Genre.all
		   render :index
		else
		  @genres = Genre.all
		   redirect_back(fallback_location: root_path)
		end

  end

  def edit
    @genre = Genre.find(params[:id])

  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      redirect_back(fallback_location: root_path)
    end
  end


 private
  def genre_params
	  params.require(:genre).permit(:name)
	end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @orders = @customer.orders.page(params[:page]).per(10)
    else
      @orders = Order.page(params[:page]).per(10)
    end
  end

  private
  def order_params
    params.require(:order).permit(:postcode, :address, :name, :payment_method,)
  end

  def address_params
    params.require(:order).permit(:postcode, :address, :name)
  end



end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def index
    if params[:word]
      @items = Item.looks(params[:word]).page(params[:page])
    else
      @items = Item.all.page(params[:page])
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
      @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
      @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :description, :genre_id, :price, :is_sold_out)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #ここの記述は、public/registrationコントローラーに記載した（しばじゅん）
  #before_action :configure_permitted_parameters, if: :devise_controller?
  #protected
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h5 class="alert alert-danger"><%= pluralize(obj.errors.count, "") %> つの項目が未入力です</h5>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/f9e80abfb4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg border-bottom">
        <div class="container">
          <div class="navbar-brand mt-3 px-3"><h2 class="logo"><%= link_to 'Nagano CAKE', root_path, class: "text-dark text-decoration-none" %></h2></div>
          <ul class="navbar-nav">
            <% if customer_signed_in? %>
              <li>
                <%= link_to customer_path(current_customer), class: "border rounded p-2 mr-3 text-dark" do %>
                <i class="fas fa-user"></i> my page
                <% end %>
              </li>
              <li>
                <%= link_to items_path, class: "border rounded p-2 mr-3 text-dark" do %>
                <i class="fas fa-birthday-cake"></i> items
                <% end %>
              </li>
              <li>
                <%= link_to cart_items_path, class: "border rounded p-2 mr-3 text-dark" do %>
                <i class="fas fa-shopping-cart"></i> cart
                <% end %>
              </li>
              <li>
                <%= link_to destroy_customer_session_path, method: :delete, class: "border rounded p-2 text-dark" do %>
                <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
            <% elsif admin_signed_in? %>
              <li>
                <%= link_to "商品一覧", admin_items_path, class: "border rounded p-2 mr-3 text-dark" %>
              </li>
              <li>
                <%= link_to "会員一覧", admin_customers_path, class: "border rounded p-2 mr-3 text-dark" %>
              </li>
              <li>
                <%= link_to "注文履歴一覧", admin_root_path, class: "border rounded p-2 mr-3 text-dark" %>
              </li>
              <li>
                <%= link_to "ジャンル一覧", admin_genres_path, class: "border rounded p-2 mr-3 text-dark" %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "border rounded p-2 text-dark" %>
              </li>
            <% else %>
              <li>
                <%= link_to about_path, class: "border rounded p-2 mr-3 text-dark" do %>
                <i class="fas fa-store"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to items_path, class: "border rounded p-2 mr-3 text-dark" do %>
                <i class="fas fa-birthday-cake"></i> items
                <% end %>
              </li>
              <li>
                <%= link_to new_customer_registration_path, class: "border rounded p-2 mr-3 text-dark" do %>
                <i class="fas fa-user-plus"></i> sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_customer_session_path, class: "border rounded p-2 mr-3 text-dark" do %>
                <i class="fas fa-sign-in-alt"></i> Log in
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        <% if admin_signed_in? %>
        <%= form_with url: admin_items_path, method: :get do |f| %>
        <div class="input-group">
          <div class="input-group-prepend">
            <%= f.label :商品名, class: "input-group-text" %>
          </div>
          <%= f.text_field :word, class: "form-control w-25", placeholder: "キーワード" %>
          <%= f.submit "検索", class: "btn text-white form-control ", style: "background-color: #a0522d;" %>
        </div>
        <% end %>
        <% end %>
        <% if customer_signed_in? %>
         <div class="d-flex justify-content-end customer_name rounded p-2 text-white"><%= current_customer.full_name %>様</div>
        <% end %>
      </nav>
    </header>
    <main><%= yield %></main>
  <footer>
    <p class="text-white">プライバシーポリシー｜よくあるご質問｜お問い合わせ｜店舗案内</p>
    <div class="text-center"><h4 class="logo"><%= link_to 'Nagano CAKE', root_path, class: "text-white text-decoration-none" %></h4></div>
    <p class="text-white text-center">©xxxx.xxxxx.xxxx</p>
  </footer>
  </body>
</html>